var searchData=
[
  ['ianimationstatecomponent_2503',['IAnimationStateComponent',['../interface_spine_1_1_unity_1_1_i_animation_state_component.html',1,'Spine::Unity']]],
  ['icons_2504',['Icons',['../class_spine_1_1_unity_1_1_editor_1_1_spine_editor_utilities_1_1_icons.html',1,'Spine::Unity::Editor::SpineEditorUtilities']]],
  ['iconstraint_2505',['IConstraint',['../interface_spine_1_1_i_constraint.html',1,'Spine']]],
  ['ihasrendererobject_2506',['IHasRendererObject',['../interface_spine_1_1_i_has_renderer_object.html',1,'Spine']]],
  ['ihasskeletoncomponent_2507',['IHasSkeletonComponent',['../interface_spine_1_1_unity_1_1_i_has_skeleton_component.html',1,'Spine::Unity']]],
  ['ihasskeletondataasset_2508',['IHasSkeletonDataAsset',['../interface_spine_1_1_unity_1_1_i_has_skeleton_data_asset.html',1,'Spine::Unity']]],
  ['ihasskeletonrenderer_2509',['IHasSkeletonRenderer',['../interface_spine_1_1_unity_1_1_i_has_skeleton_renderer.html',1,'Spine::Unity']]],
  ['ikconstraint_2510',['IkConstraint',['../class_spine_1_1_ik_constraint.html',1,'Spine']]],
  ['ikconstraintdata_2511',['IkConstraintData',['../class_spine_1_1_ik_constraint_data.html',1,'Spine']]],
  ['ikconstrainttimeline_2512',['IkConstraintTimeline',['../class_spine_1_1_ik_constraint_timeline.html',1,'Spine']]],
  ['indentscope_2513',['IndentScope',['../class_spine_1_1_unity_1_1_editor_1_1_spine_inspector_utility_1_1_indent_scope.html',1,'Spine::Unity::Editor::SpineInspectorUtility']]],
  ['intequalitycomparer_2514',['IntEqualityComparer',['../class_spine_1_1_unity_1_1_skeleton_animator_1_1_mecanim_translator_1_1_int_equality_comparer.html',1,'Spine::Unity::SkeletonAnimator::MecanimTranslator']]],
  ['ipoolable_2515',['IPoolable',['../interface_spine_1_1_pool_1_1_i_poolable.html',1,'Spine::Pool']]],
  ['iskeletonanimation_2516',['ISkeletonAnimation',['../interface_spine_1_1_unity_1_1_i_skeleton_animation.html',1,'Spine::Unity']]],
  ['iskeletoncomponent_2517',['ISkeletonComponent',['../interface_spine_1_1_unity_1_1_i_skeleton_component.html',1,'Spine::Unity']]],
  ['iupdatable_2518',['IUpdatable',['../interface_spine_1_1_i_updatable.html',1,'Spine']]]
];
